/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectIndexRouteImport } from './routes/_authenticated/project/index'
import { Route as AuthenticatedMeetingIndexRouteImport } from './routes/_authenticated/meeting/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar/index'
import { Route as AuthenticatedProjectProjectIDRouteImport } from './routes/_authenticated/project/$projectID'
import { Route as AuthenticatedMeetingMeetingIDRouteImport } from './routes/_authenticated/meeting/$meetingID'
import { Route as AuthenticatedCalendarCalendarIDRouteImport } from './routes/_authenticated/calendar/$calendarID'
import { Route as AuthenticatedProjectTaskIndexRouteImport } from './routes/_authenticated/project/task/index'
import { Route as AuthenticatedProjectTaskTaskIDRouteImport } from './routes/_authenticated/project/task/$taskID'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectIndexRoute =
  AuthenticatedProjectIndexRouteImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingIndexRoute =
  AuthenticatedMeetingIndexRouteImport.update({
    id: '/meeting/',
    path: '/meeting/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIDRoute =
  AuthenticatedProjectProjectIDRouteImport.update({
    id: '/project/$projectID',
    path: '/project/$projectID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingMeetingIDRoute =
  AuthenticatedMeetingMeetingIDRouteImport.update({
    id: '/meeting/$meetingID',
    path: '/meeting/$meetingID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarCalendarIDRoute =
  AuthenticatedCalendarCalendarIDRouteImport.update({
    id: '/calendar/$calendarID',
    path: '/calendar/$calendarID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectTaskIndexRoute =
  AuthenticatedProjectTaskIndexRouteImport.update({
    id: '/project/task/',
    path: '/project/task/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectTaskTaskIDRoute =
  AuthenticatedProjectTaskTaskIDRouteImport.update({
    id: '/project/task/$taskID',
    path: '/project/task/$taskID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/calendar/$calendarID': typeof AuthenticatedCalendarCalendarIDRoute
  '/meeting/$meetingID': typeof AuthenticatedMeetingMeetingIDRoute
  '/project/$projectID': typeof AuthenticatedProjectProjectIDRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/meeting': typeof AuthenticatedMeetingIndexRoute
  '/project': typeof AuthenticatedProjectIndexRoute
  '/project/task/$taskID': typeof AuthenticatedProjectTaskTaskIDRoute
  '/project/task': typeof AuthenticatedProjectTaskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/calendar/$calendarID': typeof AuthenticatedCalendarCalendarIDRoute
  '/meeting/$meetingID': typeof AuthenticatedMeetingMeetingIDRoute
  '/project/$projectID': typeof AuthenticatedProjectProjectIDRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/meeting': typeof AuthenticatedMeetingIndexRoute
  '/project': typeof AuthenticatedProjectIndexRoute
  '/project/task/$taskID': typeof AuthenticatedProjectTaskTaskIDRoute
  '/project/task': typeof AuthenticatedProjectTaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/calendar/$calendarID': typeof AuthenticatedCalendarCalendarIDRoute
  '/_authenticated/meeting/$meetingID': typeof AuthenticatedMeetingMeetingIDRoute
  '/_authenticated/project/$projectID': typeof AuthenticatedProjectProjectIDRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/meeting/': typeof AuthenticatedMeetingIndexRoute
  '/_authenticated/project/': typeof AuthenticatedProjectIndexRoute
  '/_authenticated/project/task/$taskID': typeof AuthenticatedProjectTaskTaskIDRoute
  '/_authenticated/project/task/': typeof AuthenticatedProjectTaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/calendar/$calendarID'
    | '/meeting/$meetingID'
    | '/project/$projectID'
    | '/calendar'
    | '/meeting'
    | '/project'
    | '/project/task/$taskID'
    | '/project/task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/calendar/$calendarID'
    | '/meeting/$meetingID'
    | '/project/$projectID'
    | '/calendar'
    | '/meeting'
    | '/project'
    | '/project/task/$taskID'
    | '/project/task'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/calendar/$calendarID'
    | '/_authenticated/meeting/$meetingID'
    | '/_authenticated/project/$projectID'
    | '/_authenticated/calendar/'
    | '/_authenticated/meeting/'
    | '/_authenticated/project/'
    | '/_authenticated/project/task/$taskID'
    | '/_authenticated/project/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/': {
      id: '/_authenticated/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthenticatedProjectIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting/': {
      id: '/_authenticated/meeting/'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof AuthenticatedMeetingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectID': {
      id: '/_authenticated/project/$projectID'
      path: '/project/$projectID'
      fullPath: '/project/$projectID'
      preLoaderRoute: typeof AuthenticatedProjectProjectIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting/$meetingID': {
      id: '/_authenticated/meeting/$meetingID'
      path: '/meeting/$meetingID'
      fullPath: '/meeting/$meetingID'
      preLoaderRoute: typeof AuthenticatedMeetingMeetingIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar/$calendarID': {
      id: '/_authenticated/calendar/$calendarID'
      path: '/calendar/$calendarID'
      fullPath: '/calendar/$calendarID'
      preLoaderRoute: typeof AuthenticatedCalendarCalendarIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/task/': {
      id: '/_authenticated/project/task/'
      path: '/project/task'
      fullPath: '/project/task'
      preLoaderRoute: typeof AuthenticatedProjectTaskIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/task/$taskID': {
      id: '/_authenticated/project/task/$taskID'
      path: '/project/task/$taskID'
      fullPath: '/project/task/$taskID'
      preLoaderRoute: typeof AuthenticatedProjectTaskTaskIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCalendarCalendarIDRoute: typeof AuthenticatedCalendarCalendarIDRoute
  AuthenticatedMeetingMeetingIDRoute: typeof AuthenticatedMeetingMeetingIDRoute
  AuthenticatedProjectProjectIDRoute: typeof AuthenticatedProjectProjectIDRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedMeetingIndexRoute: typeof AuthenticatedMeetingIndexRoute
  AuthenticatedProjectIndexRoute: typeof AuthenticatedProjectIndexRoute
  AuthenticatedProjectTaskTaskIDRoute: typeof AuthenticatedProjectTaskTaskIDRoute
  AuthenticatedProjectTaskIndexRoute: typeof AuthenticatedProjectTaskIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCalendarCalendarIDRoute: AuthenticatedCalendarCalendarIDRoute,
  AuthenticatedMeetingMeetingIDRoute: AuthenticatedMeetingMeetingIDRoute,
  AuthenticatedProjectProjectIDRoute: AuthenticatedProjectProjectIDRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedMeetingIndexRoute: AuthenticatedMeetingIndexRoute,
  AuthenticatedProjectIndexRoute: AuthenticatedProjectIndexRoute,
  AuthenticatedProjectTaskTaskIDRoute: AuthenticatedProjectTaskTaskIDRoute,
  AuthenticatedProjectTaskIndexRoute: AuthenticatedProjectTaskIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
