/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectIndexRouteImport } from './routes/_authenticated/project/index'
import { Route as AuthenticatedMessageIndexRouteImport } from './routes/_authenticated/message/index'
import { Route as AuthenticatedMeetingIndexRouteImport } from './routes/_authenticated/meeting/index'
import { Route as AuthenticatedProjectProjectIDRouteImport } from './routes/_authenticated/project/$projectID'
import { Route as AuthenticatedMeetingMeetingIDRouteImport } from './routes/_authenticated/meeting/$meetingID'
import { Route as AuthenticatedProjectTaskIndexRouteImport } from './routes/_authenticated/project/task/index'
import { Route as AuthenticatedProjectDashboardIndexRouteImport } from './routes/_authenticated/project/dashboard/index'
import { Route as AuthenticatedProjectCalendarIndexRouteImport } from './routes/_authenticated/project/calendar/index'
import { Route as AuthenticatedProjectTaskTaskIDRouteImport } from './routes/_authenticated/project/task/$taskID'
import { Route as AuthenticatedProjectSettingsSettingsRouteImport } from './routes/_authenticated/project/settings/$settings'
import { Route as AuthenticatedProjectDashboardDashboardRouteImport } from './routes/_authenticated/project/dashboard/$dashboard'
import { Route as AuthenticatedProjectCalendarCalendarIDRouteImport } from './routes/_authenticated/project/calendar/$calendarID'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectIndexRoute =
  AuthenticatedProjectIndexRouteImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessageIndexRoute =
  AuthenticatedMessageIndexRouteImport.update({
    id: '/message/',
    path: '/message/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingIndexRoute =
  AuthenticatedMeetingIndexRouteImport.update({
    id: '/meeting/',
    path: '/meeting/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIDRoute =
  AuthenticatedProjectProjectIDRouteImport.update({
    id: '/project/$projectID',
    path: '/project/$projectID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingMeetingIDRoute =
  AuthenticatedMeetingMeetingIDRouteImport.update({
    id: '/meeting/$meetingID',
    path: '/meeting/$meetingID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectTaskIndexRoute =
  AuthenticatedProjectTaskIndexRouteImport.update({
    id: '/project/task/',
    path: '/project/task/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectDashboardIndexRoute =
  AuthenticatedProjectDashboardIndexRouteImport.update({
    id: '/project/dashboard/',
    path: '/project/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectCalendarIndexRoute =
  AuthenticatedProjectCalendarIndexRouteImport.update({
    id: '/project/calendar/',
    path: '/project/calendar/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectTaskTaskIDRoute =
  AuthenticatedProjectTaskTaskIDRouteImport.update({
    id: '/project/task/$taskID',
    path: '/project/task/$taskID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectSettingsSettingsRoute =
  AuthenticatedProjectSettingsSettingsRouteImport.update({
    id: '/project/settings/$settings',
    path: '/project/settings/$settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectDashboardDashboardRoute =
  AuthenticatedProjectDashboardDashboardRouteImport.update({
    id: '/project/dashboard/$dashboard',
    path: '/project/dashboard/$dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectCalendarCalendarIDRoute =
  AuthenticatedProjectCalendarCalendarIDRouteImport.update({
    id: '/project/calendar/$calendarID',
    path: '/project/calendar/$calendarID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meeting/$meetingID': typeof AuthenticatedMeetingMeetingIDRoute
  '/project/$projectID': typeof AuthenticatedProjectProjectIDRoute
  '/meeting': typeof AuthenticatedMeetingIndexRoute
  '/message': typeof AuthenticatedMessageIndexRoute
  '/project': typeof AuthenticatedProjectIndexRoute
  '/project/calendar/$calendarID': typeof AuthenticatedProjectCalendarCalendarIDRoute
  '/project/dashboard/$dashboard': typeof AuthenticatedProjectDashboardDashboardRoute
  '/project/settings/$settings': typeof AuthenticatedProjectSettingsSettingsRoute
  '/project/task/$taskID': typeof AuthenticatedProjectTaskTaskIDRoute
  '/project/calendar': typeof AuthenticatedProjectCalendarIndexRoute
  '/project/dashboard': typeof AuthenticatedProjectDashboardIndexRoute
  '/project/task': typeof AuthenticatedProjectTaskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meeting/$meetingID': typeof AuthenticatedMeetingMeetingIDRoute
  '/project/$projectID': typeof AuthenticatedProjectProjectIDRoute
  '/meeting': typeof AuthenticatedMeetingIndexRoute
  '/message': typeof AuthenticatedMessageIndexRoute
  '/project': typeof AuthenticatedProjectIndexRoute
  '/project/calendar/$calendarID': typeof AuthenticatedProjectCalendarCalendarIDRoute
  '/project/dashboard/$dashboard': typeof AuthenticatedProjectDashboardDashboardRoute
  '/project/settings/$settings': typeof AuthenticatedProjectSettingsSettingsRoute
  '/project/task/$taskID': typeof AuthenticatedProjectTaskTaskIDRoute
  '/project/calendar': typeof AuthenticatedProjectCalendarIndexRoute
  '/project/dashboard': typeof AuthenticatedProjectDashboardIndexRoute
  '/project/task': typeof AuthenticatedProjectTaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meeting/$meetingID': typeof AuthenticatedMeetingMeetingIDRoute
  '/_authenticated/project/$projectID': typeof AuthenticatedProjectProjectIDRoute
  '/_authenticated/meeting/': typeof AuthenticatedMeetingIndexRoute
  '/_authenticated/message/': typeof AuthenticatedMessageIndexRoute
  '/_authenticated/project/': typeof AuthenticatedProjectIndexRoute
  '/_authenticated/project/calendar/$calendarID': typeof AuthenticatedProjectCalendarCalendarIDRoute
  '/_authenticated/project/dashboard/$dashboard': typeof AuthenticatedProjectDashboardDashboardRoute
  '/_authenticated/project/settings/$settings': typeof AuthenticatedProjectSettingsSettingsRoute
  '/_authenticated/project/task/$taskID': typeof AuthenticatedProjectTaskTaskIDRoute
  '/_authenticated/project/calendar/': typeof AuthenticatedProjectCalendarIndexRoute
  '/_authenticated/project/dashboard/': typeof AuthenticatedProjectDashboardIndexRoute
  '/_authenticated/project/task/': typeof AuthenticatedProjectTaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/meeting/$meetingID'
    | '/project/$projectID'
    | '/meeting'
    | '/message'
    | '/project'
    | '/project/calendar/$calendarID'
    | '/project/dashboard/$dashboard'
    | '/project/settings/$settings'
    | '/project/task/$taskID'
    | '/project/calendar'
    | '/project/dashboard'
    | '/project/task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/meeting/$meetingID'
    | '/project/$projectID'
    | '/meeting'
    | '/message'
    | '/project'
    | '/project/calendar/$calendarID'
    | '/project/dashboard/$dashboard'
    | '/project/settings/$settings'
    | '/project/task/$taskID'
    | '/project/calendar'
    | '/project/dashboard'
    | '/project/task'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/meeting/$meetingID'
    | '/_authenticated/project/$projectID'
    | '/_authenticated/meeting/'
    | '/_authenticated/message/'
    | '/_authenticated/project/'
    | '/_authenticated/project/calendar/$calendarID'
    | '/_authenticated/project/dashboard/$dashboard'
    | '/_authenticated/project/settings/$settings'
    | '/_authenticated/project/task/$taskID'
    | '/_authenticated/project/calendar/'
    | '/_authenticated/project/dashboard/'
    | '/_authenticated/project/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/': {
      id: '/_authenticated/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthenticatedProjectIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/message/': {
      id: '/_authenticated/message/'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AuthenticatedMessageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting/': {
      id: '/_authenticated/meeting/'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof AuthenticatedMeetingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectID': {
      id: '/_authenticated/project/$projectID'
      path: '/project/$projectID'
      fullPath: '/project/$projectID'
      preLoaderRoute: typeof AuthenticatedProjectProjectIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting/$meetingID': {
      id: '/_authenticated/meeting/$meetingID'
      path: '/meeting/$meetingID'
      fullPath: '/meeting/$meetingID'
      preLoaderRoute: typeof AuthenticatedMeetingMeetingIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/task/': {
      id: '/_authenticated/project/task/'
      path: '/project/task'
      fullPath: '/project/task'
      preLoaderRoute: typeof AuthenticatedProjectTaskIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/dashboard/': {
      id: '/_authenticated/project/dashboard/'
      path: '/project/dashboard'
      fullPath: '/project/dashboard'
      preLoaderRoute: typeof AuthenticatedProjectDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/calendar/': {
      id: '/_authenticated/project/calendar/'
      path: '/project/calendar'
      fullPath: '/project/calendar'
      preLoaderRoute: typeof AuthenticatedProjectCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/task/$taskID': {
      id: '/_authenticated/project/task/$taskID'
      path: '/project/task/$taskID'
      fullPath: '/project/task/$taskID'
      preLoaderRoute: typeof AuthenticatedProjectTaskTaskIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/settings/$settings': {
      id: '/_authenticated/project/settings/$settings'
      path: '/project/settings/$settings'
      fullPath: '/project/settings/$settings'
      preLoaderRoute: typeof AuthenticatedProjectSettingsSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/dashboard/$dashboard': {
      id: '/_authenticated/project/dashboard/$dashboard'
      path: '/project/dashboard/$dashboard'
      fullPath: '/project/dashboard/$dashboard'
      preLoaderRoute: typeof AuthenticatedProjectDashboardDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/calendar/$calendarID': {
      id: '/_authenticated/project/calendar/$calendarID'
      path: '/project/calendar/$calendarID'
      fullPath: '/project/calendar/$calendarID'
      preLoaderRoute: typeof AuthenticatedProjectCalendarCalendarIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeetingMeetingIDRoute: typeof AuthenticatedMeetingMeetingIDRoute
  AuthenticatedProjectProjectIDRoute: typeof AuthenticatedProjectProjectIDRoute
  AuthenticatedMeetingIndexRoute: typeof AuthenticatedMeetingIndexRoute
  AuthenticatedMessageIndexRoute: typeof AuthenticatedMessageIndexRoute
  AuthenticatedProjectIndexRoute: typeof AuthenticatedProjectIndexRoute
  AuthenticatedProjectCalendarCalendarIDRoute: typeof AuthenticatedProjectCalendarCalendarIDRoute
  AuthenticatedProjectDashboardDashboardRoute: typeof AuthenticatedProjectDashboardDashboardRoute
  AuthenticatedProjectSettingsSettingsRoute: typeof AuthenticatedProjectSettingsSettingsRoute
  AuthenticatedProjectTaskTaskIDRoute: typeof AuthenticatedProjectTaskTaskIDRoute
  AuthenticatedProjectCalendarIndexRoute: typeof AuthenticatedProjectCalendarIndexRoute
  AuthenticatedProjectDashboardIndexRoute: typeof AuthenticatedProjectDashboardIndexRoute
  AuthenticatedProjectTaskIndexRoute: typeof AuthenticatedProjectTaskIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeetingMeetingIDRoute: AuthenticatedMeetingMeetingIDRoute,
  AuthenticatedProjectProjectIDRoute: AuthenticatedProjectProjectIDRoute,
  AuthenticatedMeetingIndexRoute: AuthenticatedMeetingIndexRoute,
  AuthenticatedMessageIndexRoute: AuthenticatedMessageIndexRoute,
  AuthenticatedProjectIndexRoute: AuthenticatedProjectIndexRoute,
  AuthenticatedProjectCalendarCalendarIDRoute:
    AuthenticatedProjectCalendarCalendarIDRoute,
  AuthenticatedProjectDashboardDashboardRoute:
    AuthenticatedProjectDashboardDashboardRoute,
  AuthenticatedProjectSettingsSettingsRoute:
    AuthenticatedProjectSettingsSettingsRoute,
  AuthenticatedProjectTaskTaskIDRoute: AuthenticatedProjectTaskTaskIDRoute,
  AuthenticatedProjectCalendarIndexRoute:
    AuthenticatedProjectCalendarIndexRoute,
  AuthenticatedProjectDashboardIndexRoute:
    AuthenticatedProjectDashboardIndexRoute,
  AuthenticatedProjectTaskIndexRoute: AuthenticatedProjectTaskIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
